FROM nvidia/cuda:9.0-cudnn7-runtime-centos7

RUN yum -y install epel-release
RUN yum -y install git gcc gcc-c++ python-pip python-devel atlas atlas-devel gcc-gfortran openssl-devel libffi-devel
RUN echo ""
RUN pip install --upgrade tensorflow-gpu
RUN mkdir /test
RUN cd /test && git clone https://github.com/dsindex/tensorflow
RUN cd /test && git clone https://github.com/tensorflow/models/

RUN chown -R nobody /test

COPY cifar-10-data/ /tmp/cifar-10-data